version: '3'
services:
  notebook:
    build:
      context: ./notebook_docker
      args:
        USERID: <ENTER YOUR USERID>
    ports: 
      - "8888:8888"
    volumes:
      - <ENTER YOUR NOTEBOOK DIRECTORY>:/home/neo/notebook_workspace
    depends_on:
      - mlfields
  mlfields:
    build:
      context: ./mlfields
    environment:
        MLFIELDS_SQLALCHEMY_DATABASE_URI: 'postgresql://admin:secret@postgres:5432/mlfields'
    expose:
      - "5000"
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  postgres:
    build:
      context: ./postgres
    restart: always
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'secret'
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres-store:/var/lib/postgresql/data

volumes:
  postgres-store:
